/**
 * Kickbox
 * Kickbox API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.12-1
 *
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Kickbox) {
      root.Kickbox = {};
    }
    root.Kickbox.BalanceResponse = factory(root.Kickbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BalanceResponse model module.
   * @module model/BalanceResponse
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>BalanceResponse</code>.
   * @alias module:model/BalanceResponse
   * @class
   * @param balance {Number} A quality score of the provided email address ranging between 0 (no quality) and 1 (perfect quality). More information on the Sendex Score can be found at https://docs.kickbox.com/v2.0/docs/the-sendex
   * @param message {String} Additional information from the server
   * @param success {Boolean} true if the API request did not result in any unexpected errors
   */
  var exports = function(balance, message, success) {
    var _this = this;

    _this['balance'] = balance;
    _this['message'] = message;
    _this['success'] = success;
  };

  /**
   * Constructs a <code>BalanceResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BalanceResponse} obj Optional instance to populate.
   * @return {module:model/BalanceResponse} The populated <code>BalanceResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
      if (data.hasOwnProperty('message')) {
        obj['message'] = ApiClient.convertToType(data['message'], 'String');
      }
      if (data.hasOwnProperty('success')) {
        obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * A quality score of the provided email address ranging between 0 (no quality) and 1 (perfect quality). More information on the Sendex Score can be found at https://docs.kickbox.com/v2.0/docs/the-sendex
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;
  /**
   * Additional information from the server
   * @member {String} message
   */
  exports.prototype['message'] = undefined;
  /**
   * true if the API request did not result in any unexpected errors
   * @member {Boolean} success
   * @default true
   */
  exports.prototype['success'] = true;



  return exports;
}));


