/**
 * Kickbox
 * Kickbox API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.12-1
 *
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Kickbox) {
      root.Kickbox = {};
    }
    root.Kickbox.VerifyBatchStatusResponseProgress = factory(root.Kickbox.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The VerifyBatchStatusResponseProgress model module.
   * @module model/VerifyBatchStatusResponseProgress
   * @version 3.0.0
   */

  /**
   * Constructs a new <code>VerifyBatchStatusResponseProgress</code>.
   * Job progress
   * @alias module:model/VerifyBatchStatusResponseProgress
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>VerifyBatchStatusResponseProgress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/VerifyBatchStatusResponseProgress} obj Optional instance to populate.
   * @return {module:model/VerifyBatchStatusResponseProgress} The populated <code>VerifyBatchStatusResponseProgress</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deliverable')) {
        obj['deliverable'] = ApiClient.convertToType(data['deliverable'], 'Number');
      }
      if (data.hasOwnProperty('undeliverable')) {
        obj['undeliverable'] = ApiClient.convertToType(data['undeliverable'], 'Number');
      }
      if (data.hasOwnProperty('risky')) {
        obj['risky'] = ApiClient.convertToType(data['risky'], 'Number');
      }
      if (data.hasOwnProperty('unknown')) {
        obj['unknown'] = ApiClient.convertToType(data['unknown'], 'Number');
      }
      if (data.hasOwnProperty('total')) {
        obj['total'] = ApiClient.convertToType(data['total'], 'Number');
      }
      if (data.hasOwnProperty('unprocessed')) {
        obj['unprocessed'] = ApiClient.convertToType(data['unprocessed'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} deliverable
   */
  exports.prototype['deliverable'] = undefined;
  /**
   * @member {Number} undeliverable
   */
  exports.prototype['undeliverable'] = undefined;
  /**
   * @member {Number} risky
   */
  exports.prototype['risky'] = undefined;
  /**
   * @member {Number} unknown
   */
  exports.prototype['unknown'] = undefined;
  /**
   * @member {Number} total
   */
  exports.prototype['total'] = undefined;
  /**
   * @member {Number} unprocessed
   */
  exports.prototype['unprocessed'] = undefined;



  return exports;
}));


