/**
 * Kickbox
 * Kickbox API
 *
 * OpenAPI spec version: 3.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 1.0.12-1
 *
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiError', 'model/BalanceResponse', 'model/TrustError', 'model/VerifyBatchResponse', 'model/VerifyBatchStatusResponse', 'model/VerifyBatchStatusResponseProgress', 'model/VerifyBatchStatusResponseStats', 'model/VerifyResponse', 'api/TrustApi', 'api/VerificationApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiError'), require('./model/BalanceResponse'), require('./model/TrustError'), require('./model/VerifyBatchResponse'), require('./model/VerifyBatchStatusResponse'), require('./model/VerifyBatchStatusResponseProgress'), require('./model/VerifyBatchStatusResponseStats'), require('./model/VerifyResponse'), require('./api/TrustApi'), require('./api/VerificationApi'));
  }
}(function(ApiClient, ApiError, BalanceResponse, TrustError, VerifyBatchResponse, VerifyBatchStatusResponse, VerifyBatchStatusResponseProgress, VerifyBatchStatusResponseStats, VerifyResponse, TrustApi, VerificationApi) {
  'use strict';

  /**
   * Kickbox_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Kickbox = require('index'); // See note below*.
   * var xxxSvc = new Kickbox.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Kickbox.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Kickbox.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Kickbox.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 3.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiError model constructor.
     * @property {module:model/ApiError}
     */
    ApiError: ApiError,
    /**
     * The BalanceResponse model constructor.
     * @property {module:model/BalanceResponse}
     */
    BalanceResponse: BalanceResponse,
    /**
     * The TrustError model constructor.
     * @property {module:model/TrustError}
     */
    TrustError: TrustError,
    /**
     * The VerifyBatchResponse model constructor.
     * @property {module:model/VerifyBatchResponse}
     */
    VerifyBatchResponse: VerifyBatchResponse,
    /**
     * The VerifyBatchStatusResponse model constructor.
     * @property {module:model/VerifyBatchStatusResponse}
     */
    VerifyBatchStatusResponse: VerifyBatchStatusResponse,
    /**
     * The VerifyBatchStatusResponseProgress model constructor.
     * @property {module:model/VerifyBatchStatusResponseProgress}
     */
    VerifyBatchStatusResponseProgress: VerifyBatchStatusResponseProgress,
    /**
     * The VerifyBatchStatusResponseStats model constructor.
     * @property {module:model/VerifyBatchStatusResponseStats}
     */
    VerifyBatchStatusResponseStats: VerifyBatchStatusResponseStats,
    /**
     * The VerifyResponse model constructor.
     * @property {module:model/VerifyResponse}
     */
    VerifyResponse: VerifyResponse,
    /**
     * The TrustApi service constructor.
     * @property {module:api/TrustApi}
     */
    TrustApi: TrustApi,
    /**
     * The VerificationApi service constructor.
     * @property {module:api/VerificationApi}
     */
    VerificationApi: VerificationApi
  };

  return exports;
}));
